/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:653: Checkpoint directory /Users/davidchemaly/Documents/Cambridge/PhD_Projects/Dwarf_ZooBot/ZOO-e10-lr0.0001-bs1-seed42 exists and is not empty.
  | Name      | Type         | Params
-------------------------------------------
0 | ZOO_model | EfficientNet | 5.3 M
1 | fc1       | Linear       | 1.0 K
-------------------------------------------
5.3 M     Trainable params
0         Non-trainable params
5.3 M     Total params
21.158    Total estimated model params size (MB)

Sanity Checking DataLoader 0:   0%|                                                                                                            | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/davidchemaly/Documents/Cambridge/PhD_Projects/Dwarf_ZooBot/ZOO_lightning.py", line 245, in <module>
    trainer.fit(model, train_loader, valid_loader)
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 412, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/Users/davidchemaly/Documents/Cambridge/PhD_Projects/Dwarf_ZooBot/ZOO_lightning.py", line 142, in validation_step
    self.validation_preds.extend(preds.detach().cpu())
  File "/Users/davidchemaly/miniforge3/envs/Torch/lib/python3.10/site-packages/torch/_tensor.py", line 990, in __iter__
    raise TypeError("iteration over a 0-d tensor")
TypeError: iteration over a 0-d tensor